apiVersion: v1
description: A Helm chart for From Monolith to K8s Conference App V3
name: fmtok8s-app-v3
version: 3.0.1-SNAPSHOT
icon: https://rawgit.com/jenkins-x/jenkins-x-platform/08df980/images/kubernetes.png
